### ISSUE TITLE
新版3.4版本的问题

### ISSUE THREAD

**Issue by xiaonian233** [nszdhd1/UtilScript#3]
新版保护变得更恶心了，之前的那俩法子都不行了，如果可以的话，博主能看看吗

**Comment by nszdhd1** [comment]
有空就去看看

**Comment by xiaonian233** [comment]
{'type': 'error', 'description': 'Error: unable to intercept function at 0x7003a9cbe4; please file a bug', 'stack': 'Error: unable to intercept function at 0x7003a9cbe4; please file a bug\n    at value (frida/runtime/core.js:367)\n    at <eval> (/script1.js:51)', 'fileName': 'frida/runtime/core.js', 'lineNumber': 367, 'columnNumber': 1}

具体表现是这样的，无论怎么attach

**Comment by nszdhd1** [comment]
3.2的函数偏移，无法适用3.4。偏移需要重新分析

**Comment by xiaonian233** [comment]
我光用了il2cpp_method_get_name和il2cpp_class_get_methods
偏移分别是：0x80034F4和0x7FF12E0
不排除我找错，我感觉应该没问题
